
name: Dependencies Scan
on:
  workflow_call:

permissions:
  contents: read
  security-events: write  # ğŸ‘ˆ REQUIRED for uploading SARIF

jobs:
  container_and_sca_scan:
    name: ğŸ³ Container and Dependency Scan (Trivy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: ğŸ› ï¸ Build Docker Image
        run: docker build -t flask-app:latest -f docker/flask.dockerfile .

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ REPO / FILESYSTEM SCAN â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      - name: Trivy Repo - Sarif
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-dependency.sarif'
          severity: "CRITICAL,HIGH"
      
      - name: Trivy Repo - JSON
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-dependency.json'
          severity: "CRITICAL,HIGH"

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ CONTAINER IMAGE SCAN â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      - name: Trivy Container - Sarif
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'image'
          image-ref: flask-app:latest
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-container.sarif'
          severity: "CRITICAL,HIGH"
        
      - name: Trivy Container  - JSON
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'image'
          image-ref: flask-app:latest
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-container.json'
          severity: "CRITICAL,HIGH"

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ UPLOAD RESULTS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      - name: Upload Container scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-container.sarif'
          category: trivy-container-scan
    
      - name: Upload Dependency scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-dependency.sarif'
          category: trivy-dependency-scan


      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-container.json
            trivy-dependency.json